name: Snapshot Deploy

on:
    workflow_dispatch:

jobs:
    snapshot:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Temurin JDK 11 with Maven Central credentials and GPG
                uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version: '11'
                    # Must match the <server> id used by Maven for credentials
                    server-id: central
                    # These are variable names; values are provided via env mapping below
                    server-username: CENTRAL_USERNAME
                    server-password: CENTRAL_PASSWORD
                    # Optional for snapshots (signing not required), but harmless to keep
                    gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
                    gpg-passphrase: MAVEN_GPG_PASSPHRASE

            -   name: Export credentials for settings.xml
                env:
                    CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
                    CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
                    MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
                run: |
                    test -n "$CENTRAL_USERNAME" || (echo "CENTRAL_USERNAME not set" && exit 1)
                    test -n "$CENTRAL_PASSWORD" || (echo "CENTRAL_PASSWORD not set" && exit 1)
                    echo "Credentials ready."

            -   name: Extract project version
                id: project_version
                run: |
                    VERSION=$(mvn -B -ntp help:evaluate -Dexpression=project.version -q -DforceStdout)
                    echo "version=$VERSION" >> "$GITHUB_OUTPUT"
                    echo "Detected version: $VERSION"

            -   name: Ensure SNAPSHOT version
                run: |
                    if [[ "${{ steps.project_version.outputs.version }}" != *-SNAPSHOT ]]; then
                      echo "Project version ${{ steps.project_version.outputs.version }} is not a SNAPSHOT. Aborting snapshot deployment." >&2
                      exit 1
                    fi

            -   name: Cache Maven repository
                uses: actions/cache@v4
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-m2-

            -   name: Verify style and tests
                run: mvn -B -ntp spotless:check verify

            -   name: Deploy SNAPSHOT to Central snapshots repo
                env:
                    CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
                    CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
                    MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
                run: |
                    # Use altDeploymentRepository to avoid touching the POM's distributionManagement.
                    # Central Portal's snapshots endpoint:
                    #   https://central.sonatype.com/repository/maven-snapshots/
                    mvn -B -ntp -DskipTests \
                      -DaltDeploymentRepository=central::default::https://central.sonatype.com/repository/maven-snapshots/ \
                      deploy
